// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/verification-door/pkg/db/ent/predicate"
	"github.com/NpoolPlatform/verification-door/pkg/db/ent/usersecret"
	"github.com/google/uuid"
)

// UserSecretQuery is the builder for querying UserSecret entities.
type UserSecretQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.UserSecret
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserSecretQuery builder.
func (usq *UserSecretQuery) Where(ps ...predicate.UserSecret) *UserSecretQuery {
	usq.predicates = append(usq.predicates, ps...)
	return usq
}

// Limit adds a limit step to the query.
func (usq *UserSecretQuery) Limit(limit int) *UserSecretQuery {
	usq.limit = &limit
	return usq
}

// Offset adds an offset step to the query.
func (usq *UserSecretQuery) Offset(offset int) *UserSecretQuery {
	usq.offset = &offset
	return usq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (usq *UserSecretQuery) Unique(unique bool) *UserSecretQuery {
	usq.unique = &unique
	return usq
}

// Order adds an order step to the query.
func (usq *UserSecretQuery) Order(o ...OrderFunc) *UserSecretQuery {
	usq.order = append(usq.order, o...)
	return usq
}

// First returns the first UserSecret entity from the query.
// Returns a *NotFoundError when no UserSecret was found.
func (usq *UserSecretQuery) First(ctx context.Context) (*UserSecret, error) {
	nodes, err := usq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{usersecret.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (usq *UserSecretQuery) FirstX(ctx context.Context) *UserSecret {
	node, err := usq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserSecret ID from the query.
// Returns a *NotFoundError when no UserSecret ID was found.
func (usq *UserSecretQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = usq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{usersecret.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (usq *UserSecretQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := usq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserSecret entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one UserSecret entity is not found.
// Returns a *NotFoundError when no UserSecret entities are found.
func (usq *UserSecretQuery) Only(ctx context.Context) (*UserSecret, error) {
	nodes, err := usq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{usersecret.Label}
	default:
		return nil, &NotSingularError{usersecret.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (usq *UserSecretQuery) OnlyX(ctx context.Context) *UserSecret {
	node, err := usq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserSecret ID in the query.
// Returns a *NotSingularError when exactly one UserSecret ID is not found.
// Returns a *NotFoundError when no entities are found.
func (usq *UserSecretQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = usq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{usersecret.Label}
	default:
		err = &NotSingularError{usersecret.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (usq *UserSecretQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := usq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserSecrets.
func (usq *UserSecretQuery) All(ctx context.Context) ([]*UserSecret, error) {
	if err := usq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return usq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (usq *UserSecretQuery) AllX(ctx context.Context) []*UserSecret {
	nodes, err := usq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserSecret IDs.
func (usq *UserSecretQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := usq.Select(usersecret.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (usq *UserSecretQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := usq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (usq *UserSecretQuery) Count(ctx context.Context) (int, error) {
	if err := usq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return usq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (usq *UserSecretQuery) CountX(ctx context.Context) int {
	count, err := usq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (usq *UserSecretQuery) Exist(ctx context.Context) (bool, error) {
	if err := usq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return usq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (usq *UserSecretQuery) ExistX(ctx context.Context) bool {
	exist, err := usq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserSecretQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (usq *UserSecretQuery) Clone() *UserSecretQuery {
	if usq == nil {
		return nil
	}
	return &UserSecretQuery{
		config:     usq.config,
		limit:      usq.limit,
		offset:     usq.offset,
		order:      append([]OrderFunc{}, usq.order...),
		predicates: append([]predicate.UserSecret{}, usq.predicates...),
		// clone intermediate query.
		sql:  usq.sql.Clone(),
		path: usq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID uuid.UUID `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserSecret.Query().
//		GroupBy(usersecret.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (usq *UserSecretQuery) GroupBy(field string, fields ...string) *UserSecretGroupBy {
	group := &UserSecretGroupBy{config: usq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := usq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return usq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID uuid.UUID `json:"user_id,omitempty"`
//	}
//
//	client.UserSecret.Query().
//		Select(usersecret.FieldUserID).
//		Scan(ctx, &v)
//
func (usq *UserSecretQuery) Select(fields ...string) *UserSecretSelect {
	usq.fields = append(usq.fields, fields...)
	return &UserSecretSelect{UserSecretQuery: usq}
}

func (usq *UserSecretQuery) prepareQuery(ctx context.Context) error {
	for _, f := range usq.fields {
		if !usersecret.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if usq.path != nil {
		prev, err := usq.path(ctx)
		if err != nil {
			return err
		}
		usq.sql = prev
	}
	return nil
}

func (usq *UserSecretQuery) sqlAll(ctx context.Context) ([]*UserSecret, error) {
	var (
		nodes = []*UserSecret{}
		_spec = usq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &UserSecret{config: usq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, usq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (usq *UserSecretQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := usq.querySpec()
	return sqlgraph.CountNodes(ctx, usq.driver, _spec)
}

func (usq *UserSecretQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := usq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (usq *UserSecretQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   usersecret.Table,
			Columns: usersecret.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: usersecret.FieldID,
			},
		},
		From:   usq.sql,
		Unique: true,
	}
	if unique := usq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := usq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usersecret.FieldID)
		for i := range fields {
			if fields[i] != usersecret.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := usq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := usq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := usq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := usq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (usq *UserSecretQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(usq.driver.Dialect())
	t1 := builder.Table(usersecret.Table)
	columns := usq.fields
	if len(columns) == 0 {
		columns = usersecret.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if usq.sql != nil {
		selector = usq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range usq.predicates {
		p(selector)
	}
	for _, p := range usq.order {
		p(selector)
	}
	if offset := usq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := usq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserSecretGroupBy is the group-by builder for UserSecret entities.
type UserSecretGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (usgb *UserSecretGroupBy) Aggregate(fns ...AggregateFunc) *UserSecretGroupBy {
	usgb.fns = append(usgb.fns, fns...)
	return usgb
}

// Scan applies the group-by query and scans the result into the given value.
func (usgb *UserSecretGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := usgb.path(ctx)
	if err != nil {
		return err
	}
	usgb.sql = query
	return usgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (usgb *UserSecretGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := usgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (usgb *UserSecretGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(usgb.fields) > 1 {
		return nil, errors.New("ent: UserSecretGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := usgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (usgb *UserSecretGroupBy) StringsX(ctx context.Context) []string {
	v, err := usgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (usgb *UserSecretGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = usgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usersecret.Label}
	default:
		err = fmt.Errorf("ent: UserSecretGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (usgb *UserSecretGroupBy) StringX(ctx context.Context) string {
	v, err := usgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (usgb *UserSecretGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(usgb.fields) > 1 {
		return nil, errors.New("ent: UserSecretGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := usgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (usgb *UserSecretGroupBy) IntsX(ctx context.Context) []int {
	v, err := usgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (usgb *UserSecretGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = usgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usersecret.Label}
	default:
		err = fmt.Errorf("ent: UserSecretGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (usgb *UserSecretGroupBy) IntX(ctx context.Context) int {
	v, err := usgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (usgb *UserSecretGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(usgb.fields) > 1 {
		return nil, errors.New("ent: UserSecretGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := usgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (usgb *UserSecretGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := usgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (usgb *UserSecretGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = usgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usersecret.Label}
	default:
		err = fmt.Errorf("ent: UserSecretGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (usgb *UserSecretGroupBy) Float64X(ctx context.Context) float64 {
	v, err := usgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (usgb *UserSecretGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(usgb.fields) > 1 {
		return nil, errors.New("ent: UserSecretGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := usgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (usgb *UserSecretGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := usgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (usgb *UserSecretGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = usgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usersecret.Label}
	default:
		err = fmt.Errorf("ent: UserSecretGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (usgb *UserSecretGroupBy) BoolX(ctx context.Context) bool {
	v, err := usgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (usgb *UserSecretGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range usgb.fields {
		if !usersecret.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := usgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := usgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (usgb *UserSecretGroupBy) sqlQuery() *sql.Selector {
	selector := usgb.sql.Select()
	aggregation := make([]string, 0, len(usgb.fns))
	for _, fn := range usgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(usgb.fields)+len(usgb.fns))
		for _, f := range usgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(usgb.fields...)...)
}

// UserSecretSelect is the builder for selecting fields of UserSecret entities.
type UserSecretSelect struct {
	*UserSecretQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (uss *UserSecretSelect) Scan(ctx context.Context, v interface{}) error {
	if err := uss.prepareQuery(ctx); err != nil {
		return err
	}
	uss.sql = uss.UserSecretQuery.sqlQuery(ctx)
	return uss.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (uss *UserSecretSelect) ScanX(ctx context.Context, v interface{}) {
	if err := uss.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (uss *UserSecretSelect) Strings(ctx context.Context) ([]string, error) {
	if len(uss.fields) > 1 {
		return nil, errors.New("ent: UserSecretSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := uss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (uss *UserSecretSelect) StringsX(ctx context.Context) []string {
	v, err := uss.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (uss *UserSecretSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = uss.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usersecret.Label}
	default:
		err = fmt.Errorf("ent: UserSecretSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (uss *UserSecretSelect) StringX(ctx context.Context) string {
	v, err := uss.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (uss *UserSecretSelect) Ints(ctx context.Context) ([]int, error) {
	if len(uss.fields) > 1 {
		return nil, errors.New("ent: UserSecretSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := uss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (uss *UserSecretSelect) IntsX(ctx context.Context) []int {
	v, err := uss.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (uss *UserSecretSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = uss.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usersecret.Label}
	default:
		err = fmt.Errorf("ent: UserSecretSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (uss *UserSecretSelect) IntX(ctx context.Context) int {
	v, err := uss.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (uss *UserSecretSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(uss.fields) > 1 {
		return nil, errors.New("ent: UserSecretSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := uss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (uss *UserSecretSelect) Float64sX(ctx context.Context) []float64 {
	v, err := uss.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (uss *UserSecretSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = uss.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usersecret.Label}
	default:
		err = fmt.Errorf("ent: UserSecretSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (uss *UserSecretSelect) Float64X(ctx context.Context) float64 {
	v, err := uss.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (uss *UserSecretSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(uss.fields) > 1 {
		return nil, errors.New("ent: UserSecretSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := uss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (uss *UserSecretSelect) BoolsX(ctx context.Context) []bool {
	v, err := uss.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (uss *UserSecretSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = uss.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{usersecret.Label}
	default:
		err = fmt.Errorf("ent: UserSecretSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (uss *UserSecretSelect) BoolX(ctx context.Context) bool {
	v, err := uss.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (uss *UserSecretSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := uss.sql.Query()
	if err := uss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
