// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/verification-door/pkg/db/ent/predicate"
	"github.com/NpoolPlatform/verification-door/pkg/db/ent/usersecret"
	"github.com/google/uuid"
)

// UserSecretUpdate is the builder for updating UserSecret entities.
type UserSecretUpdate struct {
	config
	hooks    []Hook
	mutation *UserSecretMutation
}

// Where appends a list predicates to the UserSecretUpdate builder.
func (usu *UserSecretUpdate) Where(ps ...predicate.UserSecret) *UserSecretUpdate {
	usu.mutation.Where(ps...)
	return usu
}

// SetUserID sets the "user_id" field.
func (usu *UserSecretUpdate) SetUserID(u uuid.UUID) *UserSecretUpdate {
	usu.mutation.SetUserID(u)
	return usu
}

// SetSecret sets the "secret" field.
func (usu *UserSecretUpdate) SetSecret(s string) *UserSecretUpdate {
	usu.mutation.SetSecret(s)
	return usu
}

// SetCreateAt sets the "create_at" field.
func (usu *UserSecretUpdate) SetCreateAt(u uint32) *UserSecretUpdate {
	usu.mutation.ResetCreateAt()
	usu.mutation.SetCreateAt(u)
	return usu
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (usu *UserSecretUpdate) SetNillableCreateAt(u *uint32) *UserSecretUpdate {
	if u != nil {
		usu.SetCreateAt(*u)
	}
	return usu
}

// AddCreateAt adds u to the "create_at" field.
func (usu *UserSecretUpdate) AddCreateAt(u uint32) *UserSecretUpdate {
	usu.mutation.AddCreateAt(u)
	return usu
}

// SetDeleteAt sets the "delete_at" field.
func (usu *UserSecretUpdate) SetDeleteAt(u uint32) *UserSecretUpdate {
	usu.mutation.ResetDeleteAt()
	usu.mutation.SetDeleteAt(u)
	return usu
}

// SetNillableDeleteAt sets the "delete_at" field if the given value is not nil.
func (usu *UserSecretUpdate) SetNillableDeleteAt(u *uint32) *UserSecretUpdate {
	if u != nil {
		usu.SetDeleteAt(*u)
	}
	return usu
}

// AddDeleteAt adds u to the "delete_at" field.
func (usu *UserSecretUpdate) AddDeleteAt(u uint32) *UserSecretUpdate {
	usu.mutation.AddDeleteAt(u)
	return usu
}

// Mutation returns the UserSecretMutation object of the builder.
func (usu *UserSecretUpdate) Mutation() *UserSecretMutation {
	return usu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (usu *UserSecretUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(usu.hooks) == 0 {
		affected, err = usu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserSecretMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			usu.mutation = mutation
			affected, err = usu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(usu.hooks) - 1; i >= 0; i-- {
			if usu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = usu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, usu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (usu *UserSecretUpdate) SaveX(ctx context.Context) int {
	affected, err := usu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (usu *UserSecretUpdate) Exec(ctx context.Context) error {
	_, err := usu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (usu *UserSecretUpdate) ExecX(ctx context.Context) {
	if err := usu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (usu *UserSecretUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   usersecret.Table,
			Columns: usersecret.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: usersecret.FieldID,
			},
		},
	}
	if ps := usu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := usu.mutation.UserID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: usersecret.FieldUserID,
		})
	}
	if value, ok := usu.mutation.Secret(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: usersecret.FieldSecret,
		})
	}
	if value, ok := usu.mutation.CreateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersecret.FieldCreateAt,
		})
	}
	if value, ok := usu.mutation.AddedCreateAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersecret.FieldCreateAt,
		})
	}
	if value, ok := usu.mutation.DeleteAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersecret.FieldDeleteAt,
		})
	}
	if value, ok := usu.mutation.AddedDeleteAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersecret.FieldDeleteAt,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, usu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usersecret.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// UserSecretUpdateOne is the builder for updating a single UserSecret entity.
type UserSecretUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserSecretMutation
}

// SetUserID sets the "user_id" field.
func (usuo *UserSecretUpdateOne) SetUserID(u uuid.UUID) *UserSecretUpdateOne {
	usuo.mutation.SetUserID(u)
	return usuo
}

// SetSecret sets the "secret" field.
func (usuo *UserSecretUpdateOne) SetSecret(s string) *UserSecretUpdateOne {
	usuo.mutation.SetSecret(s)
	return usuo
}

// SetCreateAt sets the "create_at" field.
func (usuo *UserSecretUpdateOne) SetCreateAt(u uint32) *UserSecretUpdateOne {
	usuo.mutation.ResetCreateAt()
	usuo.mutation.SetCreateAt(u)
	return usuo
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (usuo *UserSecretUpdateOne) SetNillableCreateAt(u *uint32) *UserSecretUpdateOne {
	if u != nil {
		usuo.SetCreateAt(*u)
	}
	return usuo
}

// AddCreateAt adds u to the "create_at" field.
func (usuo *UserSecretUpdateOne) AddCreateAt(u uint32) *UserSecretUpdateOne {
	usuo.mutation.AddCreateAt(u)
	return usuo
}

// SetDeleteAt sets the "delete_at" field.
func (usuo *UserSecretUpdateOne) SetDeleteAt(u uint32) *UserSecretUpdateOne {
	usuo.mutation.ResetDeleteAt()
	usuo.mutation.SetDeleteAt(u)
	return usuo
}

// SetNillableDeleteAt sets the "delete_at" field if the given value is not nil.
func (usuo *UserSecretUpdateOne) SetNillableDeleteAt(u *uint32) *UserSecretUpdateOne {
	if u != nil {
		usuo.SetDeleteAt(*u)
	}
	return usuo
}

// AddDeleteAt adds u to the "delete_at" field.
func (usuo *UserSecretUpdateOne) AddDeleteAt(u uint32) *UserSecretUpdateOne {
	usuo.mutation.AddDeleteAt(u)
	return usuo
}

// Mutation returns the UserSecretMutation object of the builder.
func (usuo *UserSecretUpdateOne) Mutation() *UserSecretMutation {
	return usuo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (usuo *UserSecretUpdateOne) Select(field string, fields ...string) *UserSecretUpdateOne {
	usuo.fields = append([]string{field}, fields...)
	return usuo
}

// Save executes the query and returns the updated UserSecret entity.
func (usuo *UserSecretUpdateOne) Save(ctx context.Context) (*UserSecret, error) {
	var (
		err  error
		node *UserSecret
	)
	if len(usuo.hooks) == 0 {
		node, err = usuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserSecretMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			usuo.mutation = mutation
			node, err = usuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(usuo.hooks) - 1; i >= 0; i-- {
			if usuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = usuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, usuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (usuo *UserSecretUpdateOne) SaveX(ctx context.Context) *UserSecret {
	node, err := usuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (usuo *UserSecretUpdateOne) Exec(ctx context.Context) error {
	_, err := usuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (usuo *UserSecretUpdateOne) ExecX(ctx context.Context) {
	if err := usuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (usuo *UserSecretUpdateOne) sqlSave(ctx context.Context) (_node *UserSecret, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   usersecret.Table,
			Columns: usersecret.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: usersecret.FieldID,
			},
		},
	}
	id, ok := usuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing UserSecret.ID for update")}
	}
	_spec.Node.ID.Value = id
	if fields := usuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usersecret.FieldID)
		for _, f := range fields {
			if !usersecret.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usersecret.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := usuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := usuo.mutation.UserID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: usersecret.FieldUserID,
		})
	}
	if value, ok := usuo.mutation.Secret(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: usersecret.FieldSecret,
		})
	}
	if value, ok := usuo.mutation.CreateAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersecret.FieldCreateAt,
		})
	}
	if value, ok := usuo.mutation.AddedCreateAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersecret.FieldCreateAt,
		})
	}
	if value, ok := usuo.mutation.DeleteAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersecret.FieldDeleteAt,
		})
	}
	if value, ok := usuo.mutation.AddedDeleteAt(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: usersecret.FieldDeleteAt,
		})
	}
	_node = &UserSecret{config: usuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, usuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usersecret.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
