// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package npool

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VerificationDoorClient is the client API for VerificationDoor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VerificationDoorClient interface {
	// Method Version
	Version(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
}

type verificationDoorClient struct {
	cc grpc.ClientConnInterface
}

func NewVerificationDoorClient(cc grpc.ClientConnInterface) VerificationDoorClient {
	return &verificationDoorClient{cc}
}

func (c *verificationDoorClient) Version(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/verification.door.v1.VerificationDoor/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VerificationDoorServer is the server API for VerificationDoor service.
// All implementations must embed UnimplementedVerificationDoorServer
// for forward compatibility
type VerificationDoorServer interface {
	// Method Version
	Version(context.Context, *emptypb.Empty) (*VersionResponse, error)
	mustEmbedUnimplementedVerificationDoorServer()
}

// UnimplementedVerificationDoorServer must be embedded to have forward compatible implementations.
type UnimplementedVerificationDoorServer struct {
}

func (UnimplementedVerificationDoorServer) Version(context.Context, *emptypb.Empty) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (UnimplementedVerificationDoorServer) mustEmbedUnimplementedVerificationDoorServer() {}

// UnsafeVerificationDoorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VerificationDoorServer will
// result in compilation errors.
type UnsafeVerificationDoorServer interface {
	mustEmbedUnimplementedVerificationDoorServer()
}

func RegisterVerificationDoorServer(s grpc.ServiceRegistrar, srv VerificationDoorServer) {
	s.RegisterService(&VerificationDoor_ServiceDesc, srv)
}

func _VerificationDoor_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerificationDoorServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/verification.door.v1.VerificationDoor/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerificationDoorServer).Version(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// VerificationDoor_ServiceDesc is the grpc.ServiceDesc for VerificationDoor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VerificationDoor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "verification.door.v1.VerificationDoor",
	HandlerType: (*VerificationDoorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _VerificationDoor_Version_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "npool/verification-door.proto",
}
