// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// UserSecret is the predicate function for usersecret builders.
type UserSecret func(*sql.Selector)
